### ISSUE TITLE
Something is broken with 32-bit Windows on Travis

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/GitCommand.jl#18]
_Originally posted by @giordano in https://github.com/bcbi/GitCommand.jl/pull/13#issuecomment-565836038_:
> I think there is something broken with 32-bit Windows on Travis, I can't find any working setup.  It used to work.  Alex will probably try to reach out someone in Travis after the holidays.

**Comment by giordano** [comment]
This script
```yaml
language: julia
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
matrix:
  exclude:
    - os: osx
      arch: x86
  allow_failures:
    - julia: nightly
julia:
  - 1.0
  - 1.3
  - nightly
notifications:
  email: false
```
seems to work on travis-ci.org, but not on travis-ci.com :confused:
